sharding:
  dataSources:
    ds_master:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/radar?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
      username: root
      password: root
    ds_slave:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/radar?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
      username: root
      password: root
  masterSlave:
    name: ds_0
    masterDataSourceName: ds_master
    slaveDataSourceNames: ds_slave
    loadBalanceAlgorithmType: round_robin
default:
  dataSource: ds_master
spring:
  thymeleaf:
    cache: false
    encoding: UTF-8
    mode: LEGACYHTML5
  redis:
    port: 6379
    host: 127.0.0.1
    password: root
    lettuce:
      pool:
        max-idle: 10   # 最大空闲连接
        min-idle: 0   # 最小空闲链接
        max-active: 200 # 最大连接数（负数表示没有限制）
        max-wait: -1   # 最大阻塞等待时间（负数表示没有限制）
    timeout: 3000     # 链接超时时间（毫秒）
    database: 10
  #字符编码
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  messages:
    basename: i18n/messages,i18n/validationMessages
    encoding: utf-8
#activeMQ
activemq:
  brokerUrl: tcp://127.0.0.1:61616
  inMemory: true  #是否是内存模式
  password: password
  user: user
  useExponentialBackOff: true  # 是否在每次尝试重新发送失败后,增长这个等待时间
  maximumRedeliveries: 1        # 重发次数,默认为6次   这里设置为10次
  initialRedeliveryDelay: 1     # 重发时间间隔,默认为1秒
  backOffMultiplier: 2          # 第一次失败后重新发送之前等待500毫秒,第二次失败再等待500 * 2毫秒,这里的2就是value
  useCollisionAvoidance: false  # 是否避免消息碰撞
  maximumRedeliveryDelay: -1    # 设置重发最大拖延时间-1 表示没有拖延只有use-collision-avoidance(true)为true时生效
  poolMaxConnections: 5 #连接池最大连接数
  poolIdleTimeout: 30000 #空闲的链接过去时间
  poolExpiryTimeout: 0  #强制的链接过期时间
websocket:
  port: 8089
  host: 0.0.0.0
fdfs:
  so-timeout: 1500
  connect-timeout: 2000
  pool:
    max-total: 100
    max-wait-millis: 5000
  thumb-image:             #缩略图生成参数
    width: 150
    height: 150
  tracker-list:            #TrackerList参数,支持多个
    -
  web-server-url:

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.liuqi.business.model
  configuration:
    mapUnderscoreToCamelCase: true
    use-column-label: true
#pagehelper 配置
pagehelper:
  helperDialect: mysql
  reasonable: false
  support-methods-arguments: true
  params: count=countSql
#日志级别
logging:
  config: classpath:logback.xml
  level:
    com:
      liuqi:
        business:
          mapper: error
server:
  port: 8000



